openapi: "3.0.2"
info:
  version: 1.0.0
  title: Wine Quality
servers:
  - url: http://0.0.0.0:9999
paths:
  /predict:
    post:
      description: Prediction wine quality
      requestBody:
        description: List of jsons
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  fixed acidity:
                    type: number
                  volatile acidity:
                    type: number
                  citric acid:
                    type: number
                  residual sugar:
                    type: number
                  chlorides:
                    type: number
                  free sulfur dioxide:
                    type: number
                  total sulfur dioxide:
                    type: number
                  density:
                    type: number
                  pH:
                    type: number
                  sulphates:
                    type: number
                  alcohol:
                    type: number
                  color:
                    type: string

      responses:
        200:
          description: Prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  predictions:
                    type: array
                    items:
                      type: integer
  /:
    get:
      description: Hello world request
      responses:
        200:
          description: Hello world response
          content:
            text/html:
              schema:
                type: string
  /columns:
    get:
      description: Request to get list of columns
      responses:
        200:
          description: Response with list of columns
          content:
            text/html:
              schema:
                type: string